class DashboardApp {
  constructor(){this.storage=new StorageService();this.data=this.storage.load();this.settings=this.storage.settings();this.foldersService=new FolderService(this);this.websites=new WebsiteService(this);this.dialog=new Dialog(this);this.menu=new ContextMenu(this);this.search=new SearchService(this);this.theme=new ThemeService(this);this.ui=new UI(this);this.bind();this.theme.apply();this.applyLanguage();this.render()}
  get workspaceId(){return this.data.activeWorkspaceId}
  get activeWorkspace(){return this.data.workspaces.find(w=>w.id===this.workspaceId)||this.data.workspaces[0]}
  get folders(){return this.data.folders.filter(f=>f.workspaceId===this.workspaceId).sort((a,b)=>a.order-b.order)}
  get sites(){return this.data.websites.filter(w=>w.workspaceId===this.workspaceId)}
  get foldersApi(){return this.foldersService}
  persist(){this.storage.save(this.data)}
  saveSettings(){this.storage.saveSettings(this.settings)}
  t(key){const dictionary={en:{brand:'My Dashboard',search:'Search websites, folders…',newWebsite:'New website',newFolder:'New folder',all:'All',favorites:'Favorites',pinned:'Pinned',recent:'Recently Added',used:'Recently Used',workspaces:'WORKSPACES',folders:'FOLDERS',websites:'websites'},vi:{brand:'Bảng điều khiển',search:'Tìm website, thư mục…',newWebsite:'Thêm website',newFolder:'Thêm thư mục',all:'Tất cả',favorites:'Yêu thích',pinned:'Đã ghim',recent:'Mới thêm',used:'Đã dùng gần đây',workspaces:'KHÔNG GIAN LÀM VIỆC',folders:'THƯ MỤC',websites:'website'}};return dictionary[this.settings.language||'en'][key]||key}
  applyLanguage(){document.documentElement.lang=this.settings.language||'en';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=this.t(el.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=this.t(el.dataset.i18nPlaceholder))}
  render(){this.ui.render();this.bindFolderDrops()}
  bind(){document.addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(action)this.action(action)});document.querySelector('#sortSelect').onchange=e=>{this.settings.sort=e.target.value;this.saveSettings();this.ui.renderContent()};document.querySelector('#viewSelect').onchange=e=>{this.settings.view=e.target.value;this.saveSettings();this.ui.renderContent()};document.querySelector('#fileInput').onchange=e=>this.loadFile(e.target.files[0]);document.addEventListener('keydown',e=>this.shortcut(e))}
  action(action){({"new-website":()=>this.dialog.website(),"new-folder":()=>this.dialog.folder(),"new-workspace":()=>this.dialog.workspace(),settings:()=>this.dialog.settings(),export:()=>this.exportData(),import:()=>this.importData()})[action]?.()}
  bindFolderDrops(){document.querySelectorAll('[data-folder-id]').forEach(el=>{el.ondragover=e=>{e.preventDefault();el.classList.add('active')};el.ondragleave=()=>el.classList.remove('active');el.ondrop=e=>{e.preventDefault();el.classList.remove('active');const site=this.websites.find(e.dataTransfer.getData('siteId'));if(site){site.folderId=el.dataset.folderId;site.modifiedAt=Date.now();this.persist();this.render()}}})}
  openSite(site){site.lastUsed=Date.now();site.useCount++;this.persist();window.open(site.url,'_blank','noopener')}
  toggle(site,key){site[key]=!site[key];site.modifiedAt=Date.now();this.persist();this.render()}
  deleteSite(site){this.dialog.confirm(`Delete <b>${this.ui.escape(site.name)}</b>?`,()=>{this.websites.remove(site.id);this.ui.selectedId=null;this.render();this.toast('Website deleted')})}
  deleteFolder(folder){this.dialog.confirm(`Delete folder <b>${this.ui.escape(folder.name)}</b>? Its websites will be moved.`,()=>{this.foldersApi.remove(folder.id);this.render()})}
  moveDialog(site){const options=this.folders.map(f=>`<option value="${f.id}" ${site.folderId===f.id?'selected':''}>${f.name}</option>`).join('');this.dialog.show('Move website',`<div class="field"><label>Folder</label><select name="folderId">${options}</select></div>`,'Move',fd=>{site.folderId=fd.get('folderId');site.modifiedAt=Date.now();this.persist();this.render();return true})}
  reorder(sourceId,targetId){if(sourceId===targetId)return;const source=this.websites.find(sourceId),target=this.websites.find(targetId);if(!source||!target)return;const o=source.order;source.order=target.order;target.order=o;this.persist();this.render()}
  async exportData(){const payload={version:1,exportedAt:new Date().toISOString(),data:this.data,settings:this.settings};const content=JSON.stringify(payload,null,2);try{if(!window.showSaveFilePicker)throw Error('Picker unavailable');const handle=await window.showSaveFilePicker({suggestedName:'data.json',types:[{description:'Dashboard JSON',accept:{'application/json':['.json']}}]});const writer=await handle.createWritable();await writer.write(content);await writer.close();this.toast('Data saved')}catch(error){if(error.name==='AbortError')return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'application/json'}));a.download='data.json';a.click();URL.revokeObjectURL(a.href);this.toast('data.json downloaded')}}
  async importData(){try{if(!window.showOpenFilePicker)throw Error('Picker unavailable');const [handle]=await window.showOpenFilePicker({multiple:false,types:[{description:'Dashboard JSON',accept:{'application/json':['.json']}}]});this.loadFile(await handle.getFile())}catch(error){if(error.name!=='AbortError')document.querySelector('#fileInput').click()}}
  loadFile(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const payload=JSON.parse(reader.result);const d=payload.data||payload;if(!Array.isArray(d.websites)||!Array.isArray(d.folders))throw Error();this.data=d;this.settings={...this.settings,...(payload.settings||{})};if(!this.data.workspaces){this.data.workspaces=[{id:'default',name:'Personal',icon:'◈',color:'#3977ed'}];this.data.activeWorkspaceId='default';this.data.folders.forEach(f=>f.workspaceId='default');this.data.websites.forEach(w=>w.workspaceId='default')}this.persist();this.saveSettings();this.theme.apply();this.render();this.toast('Dashboard loaded')}catch{this.toast('Invalid dashboard.json')}};reader.readAsText(file);document.querySelector('#fileInput').value=''}
  shortcut(e){const tag=document.activeElement?.tagName;if(e.ctrlKey&&e.key.toLowerCase()==='k'){e.preventDefault();this.search.focus()}else if(e.ctrlKey&&e.key.toLowerCase()==='n'){e.preventDefault();this.dialog.website()}else if(tag!=='INPUT'&&tag!=='TEXTAREA'&&tag!=='SELECT'&&this.ui.selectedId){const site=this.websites.find(this.ui.selectedId);if(e.key==='Delete'){e.preventDefault();this.deleteSite(site)}if(e.key==='F2'){e.preventDefault();this.dialog.website(site)}}}
  toast(message){const t=document.createElement('div');t.className='toast';t.textContent=message;document.querySelector('#toastRoot').append(t);setTimeout(()=>t.remove(),2500)}
}
window.addEventListener('DOMContentLoaded',()=>window.dashboard=new DashboardApp());
