class UI {
  constructor(app){this.app=app;this.filter='all';this.selectedId=null}
  render(){this.renderNav();this.renderContent()}
  renderNav(){const a=this.app,count=key=>this.filtered(key).length;
    document.querySelector('#filterNav').innerHTML=[['all','▦'],['favorites','★'],['pinned','⌖'],['recent','◷'],['used','◔']].map(([id,icon])=>`<button class="nav-item ${this.filter===id?'active':''}" data-filter="${id}">${icon}<span>${a.t(id)}</span><span class="count">${count(id)}</span></button>`).join('')+`<div class="side-heading"><span>${a.t('workspaces')}</span><button class="mini-button" data-action="new-workspace">＋</button></div>`+a.data.workspaces.map(w=>`<button class="nav-item workspace ${a.workspaceId===w.id?'active':''}" data-workspace-id="${w.id}"><span class="folder-dot" style="background:${w.color}"></span><span>${w.name}</span></button>`).join('');
    document.querySelector('#folderNav').innerHTML=a.folders.map(f=>`<button class="nav-item" data-folder-id="${f.id}"><span class="folder-dot" style="background:${f.color}"></span><span>${f.icon} ${f.name}</span><span class="count">${a.sites.filter(s=>s.folderId===f.id).length}</span></button>`).join('');
    document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{this.filter=b.dataset.filter;this.render()});
    document.querySelectorAll('[data-workspace-id]').forEach(b=>b.onclick=()=>{a.data.activeWorkspaceId=b.dataset.workspaceId;a.persist();this.filter='all';this.render()});
    document.querySelectorAll('[data-folder-id]').forEach(b=>{b.onclick=()=>{this.filter=`folder:${b.dataset.folderId}`;this.render()};b.oncontextmenu=e=>a.menu.folder(e,a.folders.find(f=>f.id===b.dataset.folderId))});
  }
  filtered(filter=this.filter){let sites=[...this.app.sites].filter(s=>this.app.search.matches(s));if(filter==='all')sites=sites.filter(s=>!this.app.folders.find(f=>f.id===s.folderId)?.collapsed);if(filter==='favorites')sites=sites.filter(s=>s.favorite);if(filter==='pinned')sites=sites.filter(s=>s.pinned);if(filter==='recent')sites.sort((a,b)=>b.createdAt-a.createdAt);if(filter==='used')sites=sites.filter(s=>s.lastUsed).sort((a,b)=>b.lastUsed-a.lastUsed);if(filter.startsWith('folder:'))sites=sites.filter(s=>s.folderId===filter.slice(7));const sort=this.app.settings.sort;if(sort==='alphabet')sites.sort((a,b)=>a.name.localeCompare(b.name));if(sort==='created')sites.sort((a,b)=>b.createdAt-a.createdAt);if(sort==='modified')sites.sort((a,b)=>b.modifiedAt-a.modifiedAt);if(sort==='used')sites.sort((a,b)=>b.useCount-a.useCount);if(sort==='manual')sites.sort((a,b)=>a.order-b.order);return sites}
  renderContent(){const sites=this.filtered();const folderId=this.filter.startsWith('folder:')?this.filter.slice(7):null;const title=folderId?this.app.folders.find(f=>f.id===folderId)?.name:this.filter==='all'?this.app.t('all'):this.app.t(this.filter);document.querySelector('#pageTitle').textContent=title||this.app.t('all');document.querySelector('#pageMeta').textContent=`${sites.length} ${this.app.t('websites')} · ${this.app.activeWorkspace.name}`;document.querySelector('#sortSelect').value=this.app.settings.sort;document.querySelector('#viewSelect').value=this.app.settings.view;const pinned=this.filter==='all'?sites.filter(s=>s.pinned):[];const psec=document.querySelector('#pinnedSection');psec.classList.toggle('hidden',!pinned.length);document.querySelector('#pinnedGrid').innerHTML=pinned.map(s=>this.card(s)).join('');const content=document.querySelector('#content');content.className=`content view-${this.app.settings.view}`;content.innerHTML=sites.length?`<div class="website-grid">${sites.map(s=>this.card(s)).join('')}</div>`:`<div class="empty">${this.app.t('newWebsite')}<br><br><button class="button primary" data-action="new-website">＋ ${this.app.t('newWebsite')}</button></div>`;this.bindCards()}
  card(s){const icon=s.iconType==='upload'&&s.icon?`<img src="${s.icon}">`:s.iconType==='builtin'&&s.icon?`<i class="${s.icon}"></i>`:`<img src="${this.app.websites.favicon(s)}" onerror="this.replaceWith(document.createTextNode('◉'))">`;return `<article class="website-card ${this.selectedId===s.id?'drop-target':''}" draggable="true" data-site-id="${s.id}" style="--card-bg:${s.background};--card-text:${s.textColor}"><div class="card-accent"></div><button class="card-menu" title="More">•••</button><div class="card-content"><span class="site-icon">${icon}</span><div class="site-info"><div class="site-title">${this.escape(s.name)}</div><div class="site-url">${this.escape(s.url)}</div><div class="site-description">${this.escape(s.description)}</div></div></div><div class="badges">${s.favorite?'★':''}${s.pinned?' ⌖':''}</div></article>`}
  escape(v){const d=document.createElement('div');d.textContent=v||'';return d.innerHTML}
  bindCards(){document.querySelectorAll('[data-site-id]').forEach(el=>{const s=this.app.websites.find(el.dataset.siteId);el.onclick=e=>{if(e.target.closest('.card-menu'))return;this.selectedId=s.id;this.app.openSite(s)};el.oncontextmenu=e=>this.app.menu.site(e,s);el.querySelector('.card-menu').onclick=e=>this.app.menu.site(e,s);el.ondragstart=e=>{e.dataTransfer.setData('siteId',s.id);el.classList.add('dragging')};el.ondragend=()=>el.classList.remove('dragging');el.ondragover=e=>{e.preventDefault();el.classList.add('drop-target')};el.ondragleave=()=>el.classList.remove('drop-target');el.ondrop=e=>{e.preventDefault();el.classList.remove('drop-target');this.app.reorder(e.dataTransfer.getData('siteId'),s.id)}})}
}
